package net.minecraft.src.generators;

import net.minecraft.src.*;

public class EBGLayerBorder extends GenLayer
{
    public EBGLayerBorder(long var1, GenLayer var3)
    {
        super(var1);
        this.parent = var3;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int var1, int var2, int var3, int var4)
    {
        int[] var5 = this.parent.getInts(var1 - 1, var2 - 1, var3 + 2, var4 + 2);
        int[] var6 = IntCache.getIntCache(var3 * var4);

        for (int var7 = 0; var7 < var4; ++var7)
        {
            for (int var8 = 0; var8 < var3; ++var8)
            {
                this.initChunkSeed((long)(var8 + var1), (long)(var7 + var2));
                int var9 = var5[var8 + 1 + (var7 + 1) * (var3 + 2)];
                int var10;
                int var11;
                int var12;
                int var13;

                if (var9 != BiomeGenBase.DesertHill.biomeID && var9 != BiomeGenBase.DesertFlat.biomeID && var9 != BiomeGenBase.DesertLakes.biomeID && var9 != BiomeGenBase.DesertSavanna.biomeID && var9 != BiomeGenBase.DesertOasis.biomeID)
                {
                    if (var9 != BiomeGenBase.ColdHills.biomeID && var9 != BiomeGenBase.ColdForest1.biomeID && var9 != BiomeGenBase.ColdForest2.biomeID && var9 != BiomeGenBase.ColdForest3.biomeID)
                    {
                        var6[var8 + var7 * var3] = var9;
                    }
                    else
                    {
                        var10 = var5[var8 + 1 + (var7 + 1 - 1) * (var3 + 2)];
                        var11 = var5[var8 + 1 + 1 + (var7 + 1) * (var3 + 2)];
                        var12 = var5[var8 + 1 - 1 + (var7 + 1) * (var3 + 2)];
                        var13 = var5[var8 + 1 + (var7 + 1 + 1) * (var3 + 2)];
                        var6[var8 + var7 * var3] = var9;

                        if (var9 == BiomeGenBase.ColdHills.biomeID)
                        {
                            if (var10 != BiomeGenBase.ColdForest1.biomeID && var10 != BiomeGenBase.ColdForest2.biomeID && var10 != BiomeGenBase.ColdForest3.biomeID)
                            {
                                if (var11 != BiomeGenBase.ColdForest1.biomeID && var11 != BiomeGenBase.ColdForest2.biomeID && var11 != BiomeGenBase.ColdForest3.biomeID)
                                {
                                    if (var12 != BiomeGenBase.ColdForest1.biomeID && var12 != BiomeGenBase.ColdForest2.biomeID && var12 != BiomeGenBase.ColdForest3.biomeID)
                                    {
                                        if (var13 != BiomeGenBase.ColdForest1.biomeID && var13 != BiomeGenBase.ColdForest2.biomeID && var13 != BiomeGenBase.ColdForest3.biomeID)
                                        {
                                            var6[var8 + var7 * var3] = var9;
                                        }
                                        else
                                        {
                                            var6[var8 + var7 * var3] = BiomeGenBase.ColdHillBorder.biomeID;
                                        }
                                    }
                                    else
                                    {
                                        var6[var8 + var7 * var3] = BiomeGenBase.ColdHillBorder.biomeID;
                                    }
                                }
                                else
                                {
                                    var6[var8 + var7 * var3] = BiomeGenBase.ColdHillBorder.biomeID;
                                }
                            }
                            else
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdHillBorder.biomeID;
                            }
                        }
                        else if (var9 == BiomeGenBase.ColdForest1.biomeID)
                        {
                            if (var10 == BiomeGenBase.ColdForest2.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var11 == BiomeGenBase.ColdForest2.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var12 == BiomeGenBase.ColdForest2.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var13 == BiomeGenBase.ColdForest2.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else
                            {
                                var6[var8 + var7 * var3] = var9;
                            }
                        }
                        else if (var9 == BiomeGenBase.ColdForest2.biomeID)
                        {
                            if (var10 == BiomeGenBase.ColdForest3.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var11 == BiomeGenBase.ColdForest3.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var12 == BiomeGenBase.ColdForest3.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var13 == BiomeGenBase.ColdForest3.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else
                            {
                                var6[var8 + var7 * var3] = var9;
                            }
                        }
                        else if (var9 == BiomeGenBase.ColdForest3.biomeID)
                        {
                            if (var10 == BiomeGenBase.ColdForest1.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var11 == BiomeGenBase.ColdForest1.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var12 == BiomeGenBase.ColdForest1.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else if (var13 == BiomeGenBase.ColdForest1.biomeID)
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.ColdPlain.biomeID;
                            }
                            else
                            {
                                var6[var8 + var7 * var3] = var9;
                            }
                        }

                        if (var10 != BiomeGenBase.ColdHills.biomeID && var10 != BiomeGenBase.ColdForest1.biomeID && var10 != BiomeGenBase.ColdForest2.biomeID && var10 != BiomeGenBase.ColdForest3.biomeID)
                        {
                            var6[var8 + var7 * var3] = BiomeGenBase.ColdBorder.biomeID;
                        }
                        else if (var11 != BiomeGenBase.ColdHills.biomeID && var11 != BiomeGenBase.ColdForest1.biomeID && var11 != BiomeGenBase.ColdForest2.biomeID && var11 != BiomeGenBase.ColdForest3.biomeID)
                        {
                            var6[var8 + var7 * var3] = BiomeGenBase.ColdBorder.biomeID;
                        }
                        else if (var12 != BiomeGenBase.ColdHills.biomeID && var12 != BiomeGenBase.ColdForest1.biomeID && var12 != BiomeGenBase.ColdForest2.biomeID && var12 != BiomeGenBase.ColdForest3.biomeID)
                        {
                            var6[var8 + var7 * var3] = BiomeGenBase.ColdBorder.biomeID;
                        }
                        else if (var13 != BiomeGenBase.ColdHills.biomeID && var13 != BiomeGenBase.ColdForest1.biomeID && var13 != BiomeGenBase.ColdForest2.biomeID && var13 != BiomeGenBase.ColdForest3.biomeID)
                        {
                            var6[var8 + var7 * var3] = BiomeGenBase.ColdBorder.biomeID;
                        }
                    }
                }
                else
                {
                    var10 = var5[var8 + 1 + (var7 + 1 - 1) * (var3 + 2)];
                    var11 = var5[var8 + 1 + 1 + (var7 + 1) * (var3 + 2)];
                    var12 = var5[var8 + 1 - 1 + (var7 + 1) * (var3 + 2)];
                    var13 = var5[var8 + 1 + (var7 + 1 + 1) * (var3 + 2)];
                    var6[var8 + var7 * var3] = var9;

                    if (var9 == BiomeGenBase.DesertOasis.biomeID)
                    {
                        if (var10 != BiomeGenBase.DesertHill.biomeID && var10 != BiomeGenBase.DesertFlat.biomeID && var10 != BiomeGenBase.DesertLakes.biomeID && var10 != BiomeGenBase.DesertSavanna.biomeID)
                        {
                            if (var11 != BiomeGenBase.DesertHill.biomeID && var11 != BiomeGenBase.DesertFlat.biomeID && var11 != BiomeGenBase.DesertLakes.biomeID && var11 != BiomeGenBase.DesertSavanna.biomeID)
                            {
                                if (var12 != BiomeGenBase.DesertHill.biomeID && var12 != BiomeGenBase.DesertFlat.biomeID && var12 != BiomeGenBase.DesertLakes.biomeID && var12 != BiomeGenBase.DesertSavanna.biomeID)
                                {
                                    if (var13 != BiomeGenBase.DesertHill.biomeID && var13 != BiomeGenBase.DesertFlat.biomeID && var13 != BiomeGenBase.DesertLakes.biomeID && var13 != BiomeGenBase.DesertSavanna.biomeID)
                                    {
                                        var6[var8 + var7 * var3] = var9;
                                    }
                                    else
                                    {
                                        var6[var8 + var7 * var3] = BiomeGenBase.DesertOasisBorder.biomeID;
                                    }
                                }
                                else
                                {
                                    var6[var8 + var7 * var3] = BiomeGenBase.DesertOasisBorder.biomeID;
                                }
                            }
                            else
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.DesertOasisBorder.biomeID;
                            }
                        }
                        else
                        {
                            var6[var8 + var7 * var3] = BiomeGenBase.DesertOasisBorder.biomeID;
                        }
                    }

                    if (var9 == BiomeGenBase.DesertLakes.biomeID)
                    {
                        if (var10 != BiomeGenBase.DesertHill.biomeID && var10 != BiomeGenBase.DesertFlat.biomeID && var10 != BiomeGenBase.DesertOasis.biomeID && var10 != BiomeGenBase.DesertSavanna.biomeID)
                        {
                            if (var11 != BiomeGenBase.DesertHill.biomeID && var11 != BiomeGenBase.DesertFlat.biomeID && var11 != BiomeGenBase.DesertOasis.biomeID && var11 != BiomeGenBase.DesertSavanna.biomeID)
                            {
                                if (var12 != BiomeGenBase.DesertHill.biomeID && var12 != BiomeGenBase.DesertFlat.biomeID && var12 != BiomeGenBase.DesertOasis.biomeID && var12 != BiomeGenBase.DesertSavanna.biomeID)
                                {
                                    if (var13 != BiomeGenBase.DesertHill.biomeID && var13 != BiomeGenBase.DesertFlat.biomeID && var13 != BiomeGenBase.DesertOasis.biomeID && var13 != BiomeGenBase.DesertSavanna.biomeID)
                                    {
                                        var6[var8 + var7 * var3] = var9;
                                    }
                                    else
                                    {
                                        var6[var8 + var7 * var3] = BiomeGenBase.DesertLakeBorder.biomeID;
                                    }
                                }
                                else
                                {
                                    var6[var8 + var7 * var3] = BiomeGenBase.DesertLakeBorder.biomeID;
                                }
                            }
                            else
                            {
                                var6[var8 + var7 * var3] = BiomeGenBase.DesertLakeBorder.biomeID;
                            }
                        }
                        else
                        {
                            var6[var8 + var7 * var3] = BiomeGenBase.DesertLakeBorder.biomeID;
                        }
                    }

                    if (var10 != BiomeGenBase.DesertHill.biomeID && var10 != BiomeGenBase.DesertFlat.biomeID && var10 != BiomeGenBase.DesertOasis.biomeID && var10 != BiomeGenBase.DesertLakes.biomeID && var10 != BiomeGenBase.DesertSavanna.biomeID)
                    {
                        var6[var8 + var7 * var3] = BiomeGenBase.DesertBorder.biomeID;
                    }
                    else if (var11 != BiomeGenBase.DesertHill.biomeID && var11 != BiomeGenBase.DesertFlat.biomeID && var11 != BiomeGenBase.DesertOasis.biomeID && var11 != BiomeGenBase.DesertLakes.biomeID && var11 != BiomeGenBase.DesertSavanna.biomeID)
                    {
                        var6[var8 + var7 * var3] = BiomeGenBase.DesertBorder.biomeID;
                    }
                    else if (var12 != BiomeGenBase.DesertHill.biomeID && var12 != BiomeGenBase.DesertFlat.biomeID && var12 != BiomeGenBase.DesertOasis.biomeID && var12 != BiomeGenBase.DesertLakes.biomeID && var12 != BiomeGenBase.DesertSavanna.biomeID)
                    {
                        var6[var8 + var7 * var3] = BiomeGenBase.DesertBorder.biomeID;
                    }
                    else if (var13 != BiomeGenBase.DesertHill.biomeID && var13 != BiomeGenBase.DesertFlat.biomeID && var13 != BiomeGenBase.DesertOasis.biomeID && var13 != BiomeGenBase.DesertLakes.biomeID && var13 != BiomeGenBase.DesertSavanna.biomeID)
                    {
                        var6[var8 + var7 * var3] = BiomeGenBase.DesertBorder.biomeID;
                    }
                }
            }
        }

        return var6;
    }
}
